services:
  # MongoDB Service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "4002:27017"
    volumes:
      - mongo_data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: brishti  # Username
      MONGO_INITDB_ROOT_PASSWORD: 12345  # Password

volumes:
  mongo_data: